---
title: "Midterm_Kapuvari"
author: "Trevor Kapuvari"
date: "2023-09-25"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    number_sections: yes
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(grid)
library(gridExtra)
library(ggcorrplot) # plot correlation plot
library(corrr)      # another way to plot correlation plot
library(kableExtra)
library(jtools)     # for regression model plots
library(ggstance) # to support jtools plots
library(ggpubr)    # plotting R^2 value on ggplot point scatter
library(broom.mixed) # needed for effects plots
library(tidycensus)

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")
```

## 

```{r load_key, warning = FALSE, eval = FALSE}
census_api_key("2ad9e737f3d9062836cb46bb568be5467f86d3db", overwrite = TRUE)

acs_variable_list.2021 <- load_variables(2021, 'acs5')

house_data <- st_read("https://raw.githubusercontent.com/mafichman/musa_5080_2023/main/Midterm/data/2023/studentData.geojson")%>%
  filter(sale_price != 0)
```

```{r acs_vars, include=FALSE}
acs_vars <- c("B01001_001E", # ACS total Pop estimate
              "B25001_001E", # Estimate of total housing units
              "B25002_003E", # Number of vacant housing units
              "B19013_001E", # Median HH Income ($)
              "B14005_001E", # Total Civilians Ages 16-19
              "B14005_012E", # High School Dropouts (Male)
              "B14005_026E", # High School Dropouts (Female)
              "B19058_002E", # Households with Public Assistance Income
              "B25003_002E", # Owner Occupied Housing Units
              "B25006_002E", # Homeowner is White
              "B25006_001E") # Total Occupied Housing Units 
```

```{r get_acs_2021, message=FALSE, warning=FALSE, cache=TRUE, include=FALSE}
acsTractsPHL.2021 <- get_acs(geography = "tract",
                             year = 2021, 
                             variables = acs_vars, 
                             geometry = TRUE, 
                             state = "PA", 
                             county = "Philadelphia", 
                             output = "wide") %>%
  st_transform('EPSG:2272')
```

```{r do_some_dplyr, cache=FALSE, include=FALSE}
acsTractsPHL.2021 <- acsTractsPHL.2021 %>%
  dplyr::select (GEOID, NAME, all_of(acs_vars))

acsTractsPHL.2021 <- acsTractsPHL.2021 %>%
  rename (totalPop = B01001_001E,
          totalHU = B25001_001E,
          totalVacant = B25002_003E,
          medHHInc = B19013_001E,
          total16to19 = B14005_001E,
          HSDropoutMale = B14005_012E,
          HSDropoutFemale = B14005_026E,
          HHAssistedInc = B19058_002E,
          OwnerOccH = B25003_002E,
          WhiteHomeowner = B25006_002E,
          TotalOccH = B25006_001E)

acsTractsPHL.2021 <- acsTractsPHL.2021 %>%
  mutate(DropoutRate = (HSDropoutMale + HSDropoutFemale)/total16to19,
         HHOccupiedRate = OwnerOccH/totalHU,
         WhiteHOrate = WhiteHomeowner/TotalOccH,
         AssistedIncRate = HHAssistedInc/totalHU)
```


```{r read_github_data}
house_data <- st_read("https://raw.githubusercontent.com/mafichman/musa_5080_2023/main/Midterm/data/2023/studentData.geojson") %>%
  filter(sale_price != 0) %>%
  dplyr::select("objectid", "sale_date", "basements", "census_tract", "central_air", "exterior_condition", "fireplaces", "garage_spaces", "interior_condition", "mailing_street", "location", "number_of_bathrooms", "number_of_bedrooms", "number_stories", "sale_price") %>%
  st_transform('EPSG:2272')


#savedTidyData <- write.csv("aceTractsPHL.2021")
```


```{r get open_phily_data}
planning_districts <- st_read("https://opendata.arcgis.com/datasets/0960ea0f38f44146bb562f2b212075aa_0.geojson")%>%
  st_transform('EPSG:2272')

redevelopment_areas <- st_read("https://data-phl.opendata.arcgis.com/datasets/80f2c71305f5493c8e0aab9137354844_0.geojson") %>%
  dplyr::filter(TYPE == 'Redevelopment Area Plan and Blight Certification' & STATUS == 'Active') %>%
  st_transform('EPSG:2272')

restaurants <- st_read('https://opendata.arcgis.com/datasets/53b8a1c653a74c92b2de23a5d7bf04a0_0.geojson')%>%
  st_transform('EPSG:2272') %>%
  dplyr::select(GEOID10,TOTAL_RESTAURANTS)

restaurants <- restaurants %>%
  mutate(area_sqmi = st_area(restaurants)/358700000, #Calculate number of trees per square mile
         rest_per_mi = TOTAL_RESTAURANTS / area_sqmi)

```

``` {r get_process_tree_data}
#Get Data on trees in Philadelphia
trees <- st_read('https://opendata.arcgis.com/api/v3/datasets/5abe042f2927486891c049cf064338cb_0/downloads/data?format=geojson&spatialRefId=4326&where=1%3D1')%>%
  st_transform('EPSG:2272')

#Calculate the number of trees per census tract and convert to trees per square mile to normalize
acsTractsPHL.2021 <- st_intersection(acsTractsPHL.2021, trees) %>% #Determine what census tract each tree is in using intersection
  st_drop_geometry() %>%
  group_by(GEOID) %>% summarize(tree_count = n()) %>% #Count the number of trees in each Census tract
  right_join(acsTractsPHL.2021, by='GEOID') %>% #Join tree cont to census tract Dataframe
  st_sf() %>%
  mutate(area_sqmi = st_area(acsTractsPHL.2021)/358700000, #Calculate number of trees per square mile
         trees_per_mi = tree_count / area_sqmi)

ggplot()+
  geom_sf(data=acsTractsPHL.2021, aes(fill=q5(trees_per_mi)))+
  geom_sf(data=planning_districts,fill='transparent',color='red',linewidth=1)
```


``` {r make_maps}
 A<- ggplot()+
  geom_sf(data=house_data,aes(colour = q5(sale_price)))+
  geom_sf(data=planning_districts,fill='transparent',color='black')

B <-ggplot()+
  geom_sf(data=house_data,aes(colour = q5(sale_price)),size=0.5)+
  geom_sf(data=planning_districts,fill='transparent',color='red',linewidth=1)+
  geom_sf(data=redevelopment_areas,fill='transparent',color='black')

C <- ggplot()+
  geom_sf(data=restaurants,aes(fill = q5(rest_per_mi)))

D <- ggplot()+
  geom_sf(data=restaurants,aes(fill = q5(TOTAL_RESTAURANTS)))
```

```{r Joining All Tables}
HDJoin <- st_intersection(house_data, restaurants %>%
                               dplyr::select("TOTAL_RESTAURANTS", "rest_per_mi"))
HDJoin <- st_intersection(HDJoin, planning_districts %>%
                             dplyr::select("DIST_NAME"))
HDJoinRDAs <- HDJoin[st_intersects(HDJoin, redevelopment_areas) %>% lengths > 0, ] %>% 
  mutate(DevelopmentArea = 1)
  
NotRDAs <- HDJoin[!st_intersects(HDJoin, redevelopment_areas) %>% lengths > 0, ] %>% 
  mutate(DevelopmentArea = 0)

HDBind <- rbind(NotRDAs, HDJoinRDAs)

HDFinal <- st_intersection(house_data, acsTractsPHL.2021 %>%
                             dplyr::select(-HSDropoutMale, -HSDropoutFemale, -NAME, -total16to19))

#Start with descriptions of data and methods 
 
```

